version: '3.8'

services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        platform: linux/amd64
        container_name: sqlserver
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=PushinP!
        ports:
            - "1433:1433"
        volumes:
            - sqlserver_data:/var/opt/mssql

volumes:
    sqlserver_data:
