"""
This module provides utility functions for database connection management.

Functions:
----------
- get_connection_string():
    Constructs and returns a database connection string using environment variables.
    The connection string is formatted for use with SQL Server and the pyodbc driver.

    Environment Variables:
    - SQL_SERVER: The hostname or IP address of the SQL Server.
    - SQL_DATABASE: The name of the database to connect to.
    - SQL_USERNAME: The username for database authentication.
    - SQL_PASSWORD: The password for database authentication.
    - SQL_DRIVER: (Optional) The ODBC driver to use. Defaults to "ODBC Driver 17 for SQL Server".

- get_engine():
    Creates and returns a SQLAlchemy engine object using the connection string
    generated by `get_connection_string()`. This engine can be used to interact
    with the database.
"""
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine



load_dotenv()

def get_connection_string():
    server = os.getenv("SQL_SERVER")
    database = os.getenv("SQL_DATABASE")
    username = os.getenv("SQL_USERNAME")
    password = os.getenv("SQL_PASSWORD")
    driver = os.getenv("SQL_DRIVER", "ODBC Driver 17 for SQL Server")

    return f"mssql+pyodbc://{username}:{password}@{server}:1433/{database}?driver={driver.replace(' ', '+')}"

def get_engine():
    return create_engine(get_connection_string())

def read_sql_file(filepath):
    with open(filepath, 'r') as f:
        return f.read()